### ISSUE TITLE
would you like to share the train process?

### ISSUE THREAD

**Issue by YDS-FOREVER** [DrSleep/multi-task-refinenet#3]
I want to know how to deal the train process？And how to make the multi-task loss?
Can you give us some help?

**Comment by PaleMintBlue** [comment]
The project is very attractive. Could you share the training file? It would be really helpful!

**Comment by DrSleep** [comment]
Please refer to the example [here](https://github.com/DrSleep/DenseTorch/tree/master/examples/multitask)
